//
// Created by freedom on 2020/6/19.
//

#import <Foundation/Foundation.h>

typedef NSString *OCUITableViewDelegateKey NS_EXTENSIBLE_STRING_ENUM;

static const OCUITableViewDelegateKey OCUITableViewDelegateWillDisplayCellForRowAtIndexPathKey = @"OCUITableViewDelegateWillDisplayCellForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateWillDisplayHeaderViewForSectionKey = @"OCUITableViewDelegateWillDisplayHeaderViewForSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateWillDisplayFooterViewForSectionKey = @"OCUITableViewDelegateWillDisplayFooterViewForSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidEndDisplayingCellForRowAtIndexPathKey = @"OCUITableViewDelegateDidEndDisplayingCellForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidEndDisplayingHeaderViewForSectionKey = @"OCUITableViewDelegateDidEndDisplayingHeaderViewForSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidEndDisplayingFooterViewForSectionKey = @"OCUITableViewDelegateDidEndDisplayingFooterViewForSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateHeightForRowAtIndexPathKey = @"OCUITableViewDelegateHeightForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateHeightForHeaderInSectionKey = @"OCUITableViewDelegateHeightForHeaderInSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateHeightForFooterInSectionKey = @"OCUITableViewDelegateHeightForFooterInSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateEstimatedHeightForRowAtIndexPathKey = @"OCUITableViewDelegateEstimatedHeightForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateEstimatedHeightForHeaderInSectionKey = @"OCUITableViewDelegateEstimatedHeightForHeaderInSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateEstimatedHeightForFooterInSectionKey = @"OCUITableViewDelegateEstimatedHeightForFooterInSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateViewForHeaderInSectionKey = @"OCUITableViewDelegateViewForHeaderInSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateViewForFooterInSectionKey = @"OCUITableViewDelegateViewForFooterInSectionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateAccessoryTypeForRowWithIndexPathKey = @"OCUITableViewDelegateAccessoryTypeForRowWithIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateAccessoryButtonTappedForRowWithIndexPathKey = @"OCUITableViewDelegateAccessoryButtonTappedForRowWithIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateShouldHighlightRowAtIndexPathKey = @"OCUITableViewDelegateShouldHighlightRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidHighlightRowAtIndexPathKey = @"OCUITableViewDelegateDidHighlightRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidUnhighlightRowAtIndexPathKey = @"OCUITableViewDelegateDidUnhighlightRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateWillSelectRowAtIndexPathKey = @"OCUITableViewDelegateWillSelectRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateWillDeselectRowAtIndexPathKey = @"OCUITableViewDelegateWillDeselectRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidSelectRowAtIndexPathKey = @"OCUITableViewDelegateDidSelectRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidDeselectRowAtIndexPathKey = @"OCUITableViewDelegateDidDeselectRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateEditingStyleForRowAtIndexPathKey = @"OCUITableViewDelegateEditingStyleForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateTitleForDeleteConfirmationButtonForRowAtIndexPathKey = @"OCUITableViewDelegateTitleForDeleteConfirmationButtonForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateEditActionsForRowAtIndexPathKey = @"OCUITableViewDelegateEditActionsForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateLeadingSwipeActionsConfigurationForRowAtIndexPathKey = @"OCUITableViewDelegateLeadingSwipeActionsConfigurationForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateTrailingSwipeActionsConfigurationForRowAtIndexPathKey = @"OCUITableViewDelegateTrailingSwipeActionsConfigurationForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateShouldIndentWhileEditingRowAtIndexPathKey = @"OCUITableViewDelegateShouldIndentWhileEditingRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateWillBeginEditingRowAtIndexPathKey = @"OCUITableViewDelegateWillBeginEditingRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidEndEditingRowAtIndexPathKey = @"OCUITableViewDelegateDidEndEditingRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateTargetIndexPathForMoveFromRowAtIndexPathToProposedIndexPathKey = @"OCUITableViewDelegateTargetIndexPathForMoveFromRowAtIndexPathToProposedIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateIndentationLevelForRowAtIndexPathKey = @"OCUITableViewDelegateIndentationLevelForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateShouldShowMenuForRowAtIndexPathKey = @"OCUITableViewDelegateShouldShowMenuForRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateCanPerformActionForRowAtIndexPathWithSenderKey = @"OCUITableViewDelegateCanPerformActionForRowAtIndexPathWithSenderKey";
static const OCUITableViewDelegateKey OCUITableViewDelegatePerformActionForRowAtIndexPathWithSenderKey = @"OCUITableViewDelegatePerformActionForRowAtIndexPathWithSenderKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateCanFocusRowAtIndexPathKey = @"OCUITableViewDelegateCanFocusRowAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateShouldUpdateFocusInContextKey = @"OCUITableViewDelegateShouldUpdateFocusInContextKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidUpdateFocusInContextWithAnimationCoordinatorKey = @"OCUITableViewDelegateDidUpdateFocusInContextWithAnimationCoordinatorKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateIndexPathForPreferredFocusedViewInTableViewKey = @"OCUITableViewDelegateIndexPathForPreferredFocusedViewInTableViewKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateShouldSpringLoadRowAtIndexPathWithContextKey = @"OCUITableViewDelegateShouldSpringLoadRowAtIndexPathWithContextKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateShouldBeginMultipleSelectionInteractionAtIndexPathKey = @"OCUITableViewDelegateShouldBeginMultipleSelectionInteractionAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidBeginMultipleSelectionInteractionAtIndexPathKey = @"OCUITableViewDelegateDidBeginMultipleSelectionInteractionAtIndexPathKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateDidEndMultipleSelectionInteractionKey = @"OCUITableViewDelegateDidEndMultipleSelectionInteractionKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateContextMenuConfigurationForRowAtIndexPathPointKey = @"OCUITableViewDelegateContextMenuConfigurationForRowAtIndexPathPointKey";
static const OCUITableViewDelegateKey OCUITableViewDelegatePreviewForHighlightingContextMenuWithConfigurationKey = @"OCUITableViewDelegatePreviewForHighlightingContextMenuWithConfigurationKey";
static const OCUITableViewDelegateKey OCUITableViewDelegatePreviewForDismissingContextMenuWithConfigurationKey = @"OCUITableViewDelegatePreviewForDismissingContextMenuWithConfigurationKey";
static const OCUITableViewDelegateKey OCUITableViewDelegateWillPerformPreviewActionForMenuWithConfigurationAnimatorKey = @"OCUITableViewDelegateWillPerformPreviewActionForMenuWithConfigurationAnimatorKey";


@interface OCUITableViewDelegateWrapper : NSObject <UITableViewDelegate>

@property(nonatomic, strong, readonly) NSMutableDictionary <NSString *, id> *delegateMap;

@end